<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/confidence13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# a school pricipal is saying my college average is 80
import numpy as np
from scipy.stats import ttest_1samp
#taking sample
marks=[82,85,78,90,88,79,84,86,87,83]
#h0=80
t_statistic,p_value =ttest_1samp(marks,80)
print(np.mean(marks))
print("tstatistic",t_statistic)
print("p_vale",p_value)
alpha = 0.05
if p_value<0.5:
  print("reject ho")
else:
  print("fail to reject")

84.2
tstatistic 3.4733024324458213
p_vale 0.00701216975446086
reject ho

In [6]:
marks=[79,80,81,82,80,81,79,80,80]
#ho =80
t_stat,p_value =ttest_1samp(marks,80)
print(np.mean(marks))
print("t_stat", t_stat)
print("p_value",p_value)
alpha =0.5
if p_value<0.5:
  print("reject ho")
else:
  print("failed to reject")

80.22222222222223
t_stat 0.6859943405700548
p_value 0.512103494704045
failed to reject

In [10]:
from scipy.stats import ttest_ind
import numpy as np
old_method_marks=[70,75,72,68,74,71,69,73]
new_method_marks=[78,80,82,77,79,81,83,80]
#hooldmethod=newmethod
print("old method mean",np.mean(old_method_marks))
print("new method mean",np.mean(new_method_marks))
t_stat,p_value=ttest_ind(old_method_marks,new_method_marks)
print("t_stat",t_stat)
print("p_value",p_value)
alpha =0.5
if p_value<0.5:
  print("reject ho")
else:
  print("failed to reject")

old method mean 71.5
new method mean 80.0
t_stat -7.602631123499284
p_value 2.465359356807103e-06
reject ho

In [12]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/data cleaing/career_dataset.csv")
df

,Candidate_ID,Name,Age,Gender,Qualification,Experience_Years,Expected_Salary,Skills,City,Applied_Date
0,101,Ravi Kumar,22.0,Male,B.Tech,1.0,400000.0,Python,Hyderabad,01-01-2025
1,102,Priya Sharma,24.0,Female,MCA,2.0,500000.0,Java,Mumbai,05-01-2025
2,103,NaN,23.0,M,B.Tech,1.0,450000.0,Python,Delhi,10-01-2025
3,104,Anil Reddy,25.0,F,MBA,3.0,600000.0,SQL,Chennai,15-01-2025
4,105,Kiran,NaN,Male,B.Tech,2.0,NaN,Python,Bangalore,20-01-2025
5,106,Sita Devi,24.0,Female,NaN,NaN,480000.0,Java,Hyderabad,25-01-2025
6,107,Rahul,26.0,NaN,M.Tech,4.0,700000.0,Python,Mumbai,01-02-2025
7,108,Anu,150.0,Female,B.Tech,3.0,5000000.0,Python,NaN,05-02-2025
8,109,Vijay,23.0,Male,MBA,2.0,550000.0,SQL,Delhi,10-02-2025
9,110,Meena,24.0,F,BCA,2.0,520000.0,Java,Chennai,15-02-2025
10,111,Arjun,22.0,Male,B.Tech,1.0,450000.0,Python,Hyderabad,20-02-2025
11,112,Sneha,25.0,Female,MCA,2.0,490000.0,Java,Mumbai,25-02-2025
12,113,Kavya,27.0,M,MBA,5.0,650000.0,SQL,Delhi,01-03-2025
13,114,Rajesh,26.0,Female,M.Tech,4.0,720000.0,Python,Chennai,05-03-2025
14,115,Pooja,24.0,Male,B.Tech,3.0,580000.0,SQL,Bangalore,10-03-2025
15,116,Manoj,23.0,Female,BCA,2.0,500000.0,Java,Hyderabad,15-03-2025
16,117,Akhil,22.0,Male,MBA,1.0,470000.0,Python,Mumbai,20-03-2025
17,118,Divya,25.0,F,MCA,2.0,510000.0,Java,Delhi,25-03-2025
18,119,NaN,26.0,Female,B.Tech,20.0,530000.0,SQL,Chennai,01-04-2025
19,120,Ramesh,-5.0,Male,MBA,-1.0,-10000.0,Python,Bangalore,05-04-2025
20,103,NaN,23.0,M,B.Tech,1.0,450000.0,Python,Delhi,10-01-2025
21,106,Sita Devi,24.0,Female,NaN,NaN,480000.0,Java,Hyderabad,25-01-2025

In [13]:
print("FIRST 5 RECORDS")
print(df.head())

print("\nLAST 5 RECORDS")
print(df.tail())

print("\nSHAPE (Rows, Columns)")
print(df.shape)

print("\nCOLUMN NAMES")
print(df.columns.tolist())

print("\nDATA TYPES")
print(df.dtypes)

FIRST 5 RECORDS
   Candidate_ID          Name   Age  Gender Qualification  Experience_Years  \
0           101    Ravi Kumar  22.0    Male        B.Tech               1.0
1           102  Priya Sharma  24.0  Female           MCA               2.0
2           103           NaN  23.0       M        B.Tech               1.0
3           104    Anil Reddy  25.0       F           MBA               3.0
4           105         Kiran   NaN    Male        B.Tech               2.0

   Expected_Salary  Skills       City Applied_Date
0         400000.0  Python  Hyderabad   01-01-2025
1         500000.0    Java     Mumbai   05-01-2025
2         450000.0  Python      Delhi   10-01-2025
3         600000.0     SQL    Chennai   15-01-2025
4              NaN  Python  Bangalore   20-01-2025

LAST 5 RECORDS
    Candidate_ID       Name   Age  Gender Qualification  Experience_Years  \
17           118      Divya  25.0       F           MCA               2.0
18           119        NaN  26.0  Female        B.Tech              20.0
19           120     Ramesh  -5.0    Male           MBA              -1.0
20           103        NaN  23.0       M        B.Tech               1.0
21           106  Sita Devi  24.0  Female           NaN               NaN

    Expected_Salary  Skills       City Applied_Date
17         510000.0    Java      Delhi   25-03-2025
18         530000.0     SQL    Chennai   01-04-2025
19         -10000.0  Python  Bangalore   05-04-2025
20         450000.0  Python      Delhi   10-01-2025
21         480000.0    Java  Hyderabad   25-01-2025

SHAPE (Rows, Columns)
(22, 10)

COLUMN NAMES
['Candidate_ID', 'Name', 'Age', 'Gender', 'Qualification', 'Experience_Years', 'Expected_Salary', 'Skills', 'City', 'Applied_Date']

DATA TYPES
Candidate_ID          int64
Name                 object
Age                 float64
Gender               object
Qualification        object
Experience_Years    float64
Expected_Salary     float64
Skills               object
City                 object
Applied_Date         object
dtype: object

In [14]:
#1
num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = df.select_dtypes(include=['object']).columns.tolist()

print("\nNUMERICAL COLUMNS")
print(num_cols)

print("\nCATEGORICAL COLUMNS")
print(cat_cols)

NUMERICAL COLUMNS
['Candidate_ID', 'Age', 'Experience_Years', 'Expected_Salary']

CATEGORICAL COLUMNS
['Name', 'Gender', 'Qualification', 'Skills', 'City', 'Applied_Date']

In [16]:
print("\nMISSING VALUES BEFORE TREATMENT")
print(df.isnull().sum())

# Name → Unknown
df['Name'] = df['Name'].fillna("Unknown")

# Age → Mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Gender → Mode
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

# Qualification → Mode
df['Qualification'] = df['Qualification'].fillna(
    df['Qualification'].mode()[0]
)
# Experience_Years → Median
df['Experience_Years'] = df['Experience_Years'].fillna(
    df['Experience_Years'].median()
)

# Expected_Salary → Median
df['Expected_Salary'] = df['Expected_Salary'].fillna(
    df['Expected_Salary'].median()
)

# City → Mode
df['City'] = df['City'].fillna(df['City'].mode()[0])

print("\nMISSING VALUES AFTER TREATMENT")
print(df.isnull().sum())

MISSING VALUES BEFORE TREATMENT
Candidate_ID        0
Name                0
Age                 0
Gender              0
Qualification       0
Experience_Years    0
Expected_Salary     0
Skills              0
City                0
Applied_Date        0
dtype: int64

MISSING VALUES AFTER TREATMENT
Candidate_ID        0
Name                0
Age                 0
Gender              0
Qualification       0
Experience_Years    0
Expected_Salary     0
Skills              0
City                0
Applied_Date        0
dtype: int64

In [17]:
duplicate_count = df.duplicated().sum()

print("\nTOTAL DUPLICATES =", duplicate_count)

df = df.drop_duplicates()

print("\nDUPLICATES AFTER REMOVAL")
print(df.duplicated().sum())

TOTAL DUPLICATES = 2

DUPLICATES AFTER REMOVAL
0

In [18]:
# Gender Standardization
df['Gender'] = df['Gender'].replace({
    'M': 'Male',
    'F': 'Female'
})

# Column Names to Lowercase
df.columns = df.columns.str.lower()

print("\nUPDATED COLUMN NAMES")
print(df.columns.tolist())

UPDATED COLUMN NAMES
['candidate_id', 'name', 'age', 'gender', 'qualification', 'experience_years', 'expected_salary', 'skills', 'city', 'applied_date']

/tmp/ipykernel_902/3615041877.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Gender'] = df['Gender'].replace({

In [19]:
numerical_columns = df.select_dtypes(
    include=['int64', 'float64']
).columns

print("\nNUMERICAL COLUMNS")
print(numerical_columns)

for col in numerical_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"\nColumn: {col}")
    print("Q1 =", Q1)
    print("Q3 =", Q3)
    print("IQR =", IQR)
    print("Lower Bound =", lower_bound)
    print("Upper Bound =", upper_bound)

    df = df[
        (df[col] >= lower_bound) &
        (df[col] <= upper_bound)
    ]

print("\nOUTLIER REMOVAL COMPLETED")

NUMERICAL COLUMNS
Index(['candidate_id', 'age', 'experience_years', 'expected_salary'], dtype='object')

Column: candidate_id
Q1 = 105.75
Q3 = 115.25
IQR = 9.5
Lower Bound = 91.5
Upper Bound = 129.5

Column: age
Q1 = 23.0
Q3 = 26.0
IQR = 3.0
Lower Bound = 18.5
Upper Bound = 30.5

Column: experience_years
Q1 = 2.0
Q3 = 3.0
IQR = 1.0
Lower Bound = 0.5
Upper Bound = 4.5

Column: expected_salary
Q1 = 477500.0
Q3 = 557500.0
IQR = 80000.0
Lower Bound = 357500.0
Upper Bound = 677500.0

OUTLIER REMOVAL COMPLETED

In [20]:
df['applied_date'] = pd.to_datetime(
    df['applied_date'],
    errors='coerce'
)

print("\nDATE COLUMN TYPE")
print(df['applied_date'].dtype)

DATE COLUMN TYPE
datetime64[ns]

In [22]:
df['salary_lpa'] = df['expected_salary'] / 100000
#2
df

,candidate_id,name,age,gender,qualification,experience_years,expected_salary,skills,city,applied_date,salary_lpa
0,101,Ravi Kumar,22.000000,Male,B.Tech,1.0,400000.0,Python,Hyderabad,2025-01-01,4.0
1,102,Priya Sharma,24.000000,Female,MCA,2.0,500000.0,Java,Mumbai,2025-05-01,5.0
2,103,Unknown,23.000000,Male,B.Tech,1.0,450000.0,Python,Delhi,2025-10-01,4.5
3,104,Anil Reddy,25.000000,Female,MBA,3.0,600000.0,SQL,Chennai,NaT,6.0
4,105,Kiran,28.714286,Male,B.Tech,2.0,500000.0,Python,Bangalore,NaT,5.0
5,106,Sita Devi,24.000000,Female,B.Tech,2.0,480000.0,Java,Hyderabad,NaT,4.8
8,109,Vijay,23.000000,Male,MBA,2.0,550000.0,SQL,Delhi,2025-10-02,5.5
9,110,Meena,24.000000,Female,BCA,2.0,520000.0,Java,Chennai,NaT,5.2
10,111,Arjun,22.000000,Male,B.Tech,1.0,450000.0,Python,Hyderabad,NaT,4.5
11,112,Sneha,25.000000,Female,MCA,2.0,490000.0,Java,Mumbai,NaT,4.9
14,115,Pooja,24.000000,Male,B.Tech,3.0,580000.0,SQL,Bangalore,2025-10-03,5.8
15,116,Manoj,23.000000,Female,BCA,2.0,500000.0,Java,Hyderabad,NaT,5.0
16,117,Akhil,22.000000,Male,MBA,1.0,470000.0,Python,Mumbai,NaT,4.7
17,118,Divya,25.000000,Female,MCA,2.0,510000.0,Java,Delhi,NaT,5.1

In [23]:
def experience_category(exp):

    if exp <= 2:
        return "Fresher"

    elif exp <= 5:
        return "Intermediate"

    else:
        return "Experienced"

df['experience_category'] = (
    df['experience_years']
    .apply(experience_category)

SyntaxError: incomplete input (1852507667.py, line 14)

In [24]:
ef age_group(age):

    if age < 25:
        return "Young"

    elif age <= 30:
        return "Mid-Level"

    else:
        return "Senior"

df['age_group'] = df['age'].apply(age_group)

SyntaxError: invalid syntax (676937723.py, line 1)