<a href="https://colab.research.google.com/github/bharathrockstar813-byte/e-commerce-/blob/main/outliters1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import numpy as np
data = [2,4,5,6,7,8,9,100]
#step1 Q1, Q3
Q1 = np.percentile(data,25)
Q3 = np.percentile(data, 75)
print(Q1,Q3)
IQR = Q3 -Q1
print(IQR)
lower = Q1-1.5*IQR
upper = Q3+1.5*IQR
print(lower)
print(upper)
outliers = []
for i in data:
  if i<lower or i>upper:
    outliers.append(i)
print(outliers)
cleaned_outliers = []
for i in data:
  if lower<=i<=upper:
    cleaned_outliers.append(i)
print(cleaned_outliers)

4.75 8.25
3.5
-0.5
13.5
[100]
[2, 4, 5, 6, 7, 8, 9]

In [23]:
import pandas as pd

In [24]:
df=pd.read_csv("/content/drive/MyDrive/data cleaing/student_marks_outlier_dataset.csv")

In [25]:
df

    Student_ID  Marks
0            1     58
1            2     62
2            3     65
3            4     67
4            5     69
5            6     70
6            7     71
7            8     72
8            9     73
9           10     74
10          11     75
11          12     76
12          13     78
13          14     80
14          15     82
15          16     84
16          17     85
17          18     87
18          19     90
19          20    250

In [26]:
df.columns

Index(['Student_ID', 'Marks'], dtype='object')

In [46]:
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)
IQR = Q3-Q1
lower_limit = Q1-1.5*IQR
upper_limit = Q3+1.5*IQR
outliers = df[
    (df["Marks"]<lower_limit)  |
    (df["Marks"]>upper_limit)
]
print(outliers)
df.drop(19, inplace=True)

Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Marks, City]
Index: []

KeyError: '[19] not found in axis'

In [32]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/drive/MyDrive/data cleaing/student_dataset_20rows.csv")

In [34]:
df

    Student_ID     Name  Age            Course  Marks         City
0          101      Ram   25            Pandas     90   Vijayawada
1          102     Ravi   23             NumPy     81    Hyderabad
2          103     Sita   21            Python     80      Chennai
3          104    Kiran   21      Data Science     98    Bangalore
4          105      Anu   20            Pandas     70       Mumbai
5          106    Rahul   22               SQL     82        Delhi
6          107    Sneha   25     Deep Learning     79         Pune
7          108    Arjun   22  Machine Learning     70      Kolkata
8          109    Pooja   20            Python     95        Vizag
9          110   Vikram   20               SQL     72     Tirupati
10         111    Divya   23     Deep Learning     94     Warangal
11         112     Ajay   21            Python     84       Guntur
12         113  Keerthi   21             NumPy     74      Nellore
13         114   Nikhil   22     Deep Learning     99       Kadapa
14         115    Meena   23                AI     81      Kurnool
15         116      Sai   25            Pandas     97       Ongole
16         117  Lavanya   20                AI     72  Rajahmundry
17         118    Rohit   23            Python     70        Eluru
18         119     Teja   25  Machine Learning     90      Khammam
19         120    Priya   22               SQL     78    Nizamabad

In [35]:
print("mean",df["Marks"].mean())
print("median",df["Marks"].median())
print("mode",df["Marks"].mode())

mean 82.8
median 81.0
mode 0    70
Name: Marks, dtype: int64

In [36]:
#dispersion
print("variance",df["Marks"].var())
print("stamdard deviation",df["Marks"].std())

variance 101.53684210526318
stamdard deviation 10.076549116898263

In [37]:
#quartli0es
q1=df["Marks"].quantile(0.25)
q2=df["Marks"].quantile(0.50)
q3=df["Marks"].quantile(0.75)
print(q1,q2,q3)

73.5 81.0 91.0

In [44]:
skewenss=df["Marks"].skew()
print(skewness)
if skewness>0:
   print("postivley skewed")
elif skewness<0:
  print("negatively skewed")
else:
    print("symteric distribution")

0.20361555880041018
postivley skewed

In [45]:
Q1 = df["Marks"].quantile(0.25)
Q3 = df["Marks"].quantile(0.75)
IQR = Q3-Q1
lower_limit = Q1-1.5*IQR
upper_limit = Q3+1.5*IQR
outliers = df[
    (df["Marks"]<lower_limit)  |
    (df["Marks"]>upper_limit)
]
print(outliers)

Empty DataFrame
Columns: [Student_ID, Name, Age, Course, Marks, City]
Index: []